In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
import seaborn as sns
import glob
import matplotlib.pyplot as plt

In [2]:
hour_price_df = pd.read_csv('electricity_prices_helsinki.csv')
hour_price_df

                      hour   price
0      2023-01-01 00:00:00    4.84
1      2023-01-01 01:00:00    2.01
2      2023-01-01 02:00:00    1.38
3      2023-01-01 03:00:00    0.09
4      2023-01-01 04:00:00    0.08
...                    ...     ...
26299  2025-12-31 19:00:00  152.00
26300  2025-12-31 20:00:00  140.00
26301  2025-12-31 21:00:00  131.41
26302  2025-12-31 22:00:00  129.91
26303  2025-12-31 23:00:00  115.73

[26304 rows x 2 columns]

In [3]:
hour_price_df.info();hour_price_df.describe();hour_price_df.head()

<class 'pandas.DataFrame'>
RangeIndex: 26304 entries, 0 to 26303
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   hour    26304 non-null  str
 1   price   26304 non-null  float64
dtypes: float64(1), str(1)
memory usage: 411.1 KB

                  hour  price
0  2023-01-01 00:00:00   4.84
1  2023-01-01 01:00:00   2.01
2  2023-01-01 02:00:00   1.38
3  2023-01-01 03:00:00   0.09
4  2023-01-01 04:00:00   0.08

In [15]:
hour_price_df["hour"] = pd.to_datetime(hour_price_df["hour"])

hour_price_df.info();hour_price_df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 26304 entries, 0 to 26303
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   hour    26304 non-null  datetime64[us]
 1   price   26304 non-null  float64
dtypes: datetime64[us](1), float64(1)
memory usage: 411.1 KB

                             hour         price
count                       26304  26304.000000
mean   2024-07-02 00:04:52.335766     47.500456
min           2023-01-01 00:00:00   -500.000000
25%           2023-10-02 00:45:00      5.237500
50%           2024-07-02 00:30:00     29.770000
75%           2025-04-02 00:15:00     72.562500
max           2025-12-31 23:00:00   1896.000000
std                           NaN     62.366108

In [16]:
hour_price_df.sample(5)

                     hour  price
12119 2024-05-20 00:00:00  -0.31
905   2023-02-07 17:00:00  59.24
13039 2024-06-27 08:00:00  32.91
8401  2023-12-17 01:00:00  -1.10
1976  2023-03-24 08:00:00  58.59